// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxDataAPI.Context;


#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(ZipCodeContext))]
    partial class ZipCodeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Models.ZipCode", b =>
                {
                    b.Property<string>("UniqueZip")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("zip_code");

                    b.Property<int>("AdjustGrossIncomeSize")
                        .HasColumnType("int")
                        .HasColumnName("AGI_size");

                    b.Property<int>("AdjustedGrossIncome")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("SUM([adjusted_gross_income])");

                    b.Property<int>("NumberOfIndividuals")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("SUM([number_of_individuals])");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("state_abbreviation");

                    b.Property<int>("TaxableIncomeAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("SUM([taxable_income_amount])");

                    b.Property<int>("TotalIncome")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("SUM([total_income_amount])");

                    b.Property<int>("TotalSalaryAndWages")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("SUM([total_income_amount])");

                    b.HasKey("UniqueZip");

                    b.ToTable("ZipCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
